// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs4KSHhwVFtOBO67eVy0CvrnWrRf7NS40',
    appId: '1:110623889403:web:3954f56fae0c2cfb521d5e',
    messagingSenderId: '110623889403',
    projectId: 'uniduniapp-15768',
    authDomain: 'uniduniapp-15768.firebaseapp.com',
    storageBucket: 'uniduniapp-15768.appspot.com',
    measurementId: 'G-D65GVE0KK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaE8gQIGr3E7XgzSRemTLfAKMMvv82ik4',
    appId: '1:110623889403:android:9c0a759d33edf8d4521d5e',
    messagingSenderId: '110623889403',
    projectId: 'uniduniapp-15768',
    storageBucket: 'uniduniapp-15768.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd4XTiOLLQ7uRC1Nwj2vCZNPqOrPpJGbE',
    appId: '1:110623889403:ios:8e2858498f4db0bd521d5e',
    messagingSenderId: '110623889403',
    projectId: 'uniduniapp-15768',
    storageBucket: 'uniduniapp-15768.appspot.com',
    iosBundleId: 'com.example.projetoP2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd4XTiOLLQ7uRC1Nwj2vCZNPqOrPpJGbE',
    appId: '1:110623889403:ios:4d83aaef6c840a07521d5e',
    messagingSenderId: '110623889403',
    projectId: 'uniduniapp-15768',
    storageBucket: 'uniduniapp-15768.appspot.com',
    iosBundleId: 'uniduni.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs4KSHhwVFtOBO67eVy0CvrnWrRf7NS40',
    appId: '1:110623889403:web:654df1e80bb12573521d5e',
    messagingSenderId: '110623889403',
    projectId: 'uniduniapp-15768',
    authDomain: 'uniduniapp-15768.firebaseapp.com',
    storageBucket: 'uniduniapp-15768.appspot.com',
    measurementId: 'G-9LZSBQE6EK',
  );

}